[project]
authors = [
  {name = "Lengyue", email = "lengyue@lengyue.me"},
]
dependencies = [
]
description = "Preprocess audio data"
license = {text = "Apache"}
name = "fish-audio-preprocess"
readme = "README.md"
requires-python = ">=3.9"
version = "0.2.8"

[project.scripts]
fap = "fish_audio_preprocess.cli.__main__:cli"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[tool.setuptools]
packages = ["fish_audio_preprocess"]

[tool.isort]
profile = "black"
